name: Cron test

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show scheduled run
        run: |
          echo "Cron test started"
          date -u
